apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  selector:
    app: tracing
    microservice: jaeger
  type: NodePort
  ports:
    - port: 80
      targetPort: 16686
      protocol: TCP
      name: http
    - port: 6831
      targetPort: 6831
      protocol: UDP
      name: udp
    - port: 4318
      targetPort: 4318
      protocol: TCP
      name: grpc
    - port: 4317
      targetPort: 4317
      protocol: UDP
      name: grpc-udp