sonar.organization=gowtham-devops
sonar.projectKey=tracing-jaeger-client
sonar.projectName=Jaeger Client
sonar.sources=app/src/main/java
sonar.tests=app/src/test/java
sonar.java.binaries=app/target/classes
sonar.java.test.binaries=app/target/test-classes