sonar.organization=gowtham-devops
sonar.projectKey=tracing-jaeger-client
sonar.projectName=Jaeger Client
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes