name: code analysis - server
on: 
  push:
    branches:
      - master
    paths:
      - 'jaeger-server/**'
      - '.github/workflows/Code analysis server.yaml'      
  workflow_dispatch:
jobs:
  code-analysis:
    environment: General
    name: Code analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: maven
      - run: cd jaeger-server && mvn compile package
      - name: sonarqube static code analyze
        uses: sonarSource/sonarqube-scan-action@v7.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: 'jaeger-server'
      - name: Build Docker Image
        run: docker build -t tracing-server:latest jaeger-server/
      - name: docker image scan with trivy
        uses: NullPointerWorks/trivy-image-scan-action@v1
        with:
          image-name: tracing-server:latest


        