name: SonarQube & trivy code analysis -client
on: 
  push:
    branches:
      - master
    paths:
      - 'jaeger-client/**'
      - '.github/workflows/Code analysis client.yaml'      
  workflow_dispatch:
jobs:
  code-analysis:
    environment: General
    name: Code analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: maven
      - run: cd jaeger-client && mvn compile package
      - name: create sonar-project.properties file
        run: |
          ls -la
          echo "sonar.projectKey=jaeger-client" > jaeger-client/sonar-project.properties
          echo "sonar.projectName=Jaeger Client" >> jaeger-client/sonar-project.properties
          echo "sonar.organization=gowtham-devops" >> jaeger-client/sonar-project.properties
          echo "sonar.sources=src/main/java" >> jaeger-client/sonar-project.properties
          echo "sonar.tests=src/test/java" >> jaeger-client/sonar-project.properties
          echo "sonar.java.binaries=target/classes" >> jaeger-client/sonar-project.properties
     # - run: cd app &&mvn clean test jacoco:report sonar:sonar    
      - name: sonarqube static code analyze
        uses: sonarSource/sonarqube-scan-action@v7.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}\
        with:
          projectBaseDir: 'jaeger-client'
      - name: Build Docker Image
        run: docker build -t java-app:latest app/
      - name: docker image scan with trivy
        uses: NullPointerWorks/trivy-image-scan-action@v1
        with:
          image-name: tracing-client:latest

          
        