name: SonarQube & trivy code analysis - server
on: 
  push:
    branches:
      - master
    paths:
      - 'jaeger-server/**'
      - '.github/workflows/bulid server.yaml'      
  workflow_dispatch:
jobs:
  code-analysis:
    environment: General
    name: Code analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'
          cache: maven
      - run: cd jaeger-server && mvn compile package
     # - run: cd app &&mvn clean test jacoco:report sonar:sonar
      - name: sonarqube static code analyze
        uses: sonarSource/sonarqube-scan-action@v7.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Build Docker Image
        run: docker build -t java-app:latest app/
      - name: docker image scan with trivy
        uses: NullPointerWorks/trivy-image-scan-action@v1
        with:
          image-name: java-app:latest
        